apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noami-nobodu4788-next-page-router-zips
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/noami-nobodu4788-next-page-router-zips.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: noami-nobodu4788-next-page-router-zips
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
