apiVersion: apps/v1
kind: Deployment
metadata:
  name: noami-nobodu4788-next-page-router-zips-deployment
  labels:
    app: noami-nobodu4788-next-page-router-zips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noami-nobodu4788-next-page-router-zips
  template:
    metadata:
      labels:
        app: noami-nobodu4788-next-page-router-zips
    spec:
      containers:
        - name: noami-nobodu4788-next-page-router-zips-container
          image: pipejet/noami-nobodu4788-next-page-router-zips:latest
          ports:
            - containerPort: 3000
